# Generated by Django 5.1 on 2024-10-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='user',
            new_name='author',
        ),
    ]
